const mongoose = require("mongoose");
const { Schema } = mongoose;
var aggregatePaginate = require("mongoose-aggregate-paginate-v2");

const bloodFormSchema = new mongoose.Schema(
  {
    fullName: {
      type: String,
      required: true,
    },
    email: {
      type: String,
      required: true,
    },
    mobileNo: {
      type: String,
      required: true,
    },
    gender: {
      type: String,
      required: true,
      enum: ["male", "female", "other"],
    },
    age: {
      type: Number,
      required: true,
    },
    bloodGroup: {
      type: String,
      required: true,
      enum: ["O+", "A+", "B+", "AB+", "O-", "A-", "B-", "AB-"],
    },
    quantity: {
      type: Number,
      required: true,
    },
    address: {
      type: String,
      required: true,
    },
    district: {
      type: String,
      required: true,
    },
    pincode: {
      type: String,
      required: true,
    },
    reqPersonAddhar: {
      type: String,
    },
    formType: {
      type: String,
      enum: ["DonateBlood", "Bloodrequest"],
      required: true,
    },
    submittedBy: {
      type: Schema.Types.ObjectId,
      ref: "User",
    },
    timestamp: {
      type: Date,
      default: Date.now,
    },
  },
  { timestamps: true },
);

bloodFormSchema.plugin(aggregatePaginate);
const BloodForm = mongoose.model("BloodForm", bloodFormSchema);

const dummyData = [
  {
    fullName: "John Doe",
    email: "john.doe@example.com",
    mobileNo: "9876543210",
    gender: "male",
    age: 30,
    bloodGroup: "O+",
    quantity: 1,
    address: "123 Main Street",
    district: "Bhubaneswar",
    pincode: "751001",
    reqPersonAddhar: "123456789012",
    formType: "bloodRequest",
  },
  {
    fullName: "Jane Smith",
    email: "jane.smith@example.com",
    mobileNo: "9876543211",
    gender: "female",
    age: 25,
    bloodGroup: "A+",
    quantity: 2,
    address: "456 Oak Avenue",
    district: "Cuttack",
    pincode: "753001",
    reqPersonAddhar: "123456789013",
    formType: "bloodDonation",
  },
  {
    fullName: "Michael Johnson",
    email: "michael.johnson@example.com",
    mobileNo: "9876543212",
    gender: "male",
    age: 35,
    bloodGroup: "B+",
    quantity: 1,
    address: "789 Pine Street",
    district: "Rourkela",
    pincode: "769001",
    reqPersonAddhar: "123456789014",
    formType: "bloodRequest",
  },
  {
    fullName: "Sarah Brown",
    email: "sarah.brown@example.com",
    mobileNo: "9876543213",
    gender: "female",
    age: 28,
    bloodGroup: "AB+",
    quantity: 2,
    address: "1010 Maple Avenue",
    district: "Puri",
    pincode: "752001",
    reqPersonAddhar: "123456789015",
    formType: "bloodDonation",
  },
  {
    fullName: "Christopher Lee",
    email: "chris.lee@example.com",
    mobileNo: "9876543214",
    gender: "male",
    age: 40,
    bloodGroup: "O-",
    quantity: 1,
    address: "222 Elm Street",
    district: "Sambalpur",
    pincode: "768001",
    reqPersonAddhar: "123456789016",
    formType: "bloodRequest",
  },
  {
    fullName: "Emily Davis",
    email: "emily.davis@example.com",
    mobileNo: "9876543215",
    gender: "female",
    age: 22,
    bloodGroup: "B-",
    quantity: 2,
    address: "333 Oak Lane",
    district: "Berhampur",
    pincode: "760001",
    reqPersonAddhar: "123456789017",
    formType: "bloodDonation",
  },
  {
    fullName: "Matthew Wilson",
    email: "matthew.wilson@example.com",
    mobileNo: "9876543216",
    gender: "male",
    age: 45,
    bloodGroup: "A-",
    quantity: 1,
    address: "444 Maple Road",
    district: "Balasore",
    pincode: "756001",
    reqPersonAddhar: "123456789018",
    formType: "bloodRequest",
  },
  {
    fullName: "Olivia Taylor",
    email: "olivia.taylor@example.com",
    mobileNo: "9876543217",
    gender: "female",
    age: 27,
    bloodGroup: "AB-",
    quantity: 2,
    address: "555 Pine Avenue",
    district: "Baripada",
    pincode: "757001",
    reqPersonAddhar: "123456789019",
    formType: "bloodDonation",
  },
  {
    fullName: "William Jones",
    email: "william.jones@example.com",
    mobileNo: "9876543218",
    gender: "male",
    age: 32,
    bloodGroup: "O+",
    quantity: 1,
    address: "666 Oak Street",
    district: "Koraput",
    pincode: "764001",
    reqPersonAddhar: "123456789020",
    formType: "bloodRequest",
  },
  {
    fullName: "Ava Brown",
    email: "ava.brown@example.com",
    mobileNo: "9876543219",
    gender: "female",
    age: 29,
    bloodGroup: "A+",
    quantity: 2,
    address: "777 Pine Lane",
    district: "Bargarh",
    pincode: "768001",
    reqPersonAddhar: "123456789021",
    formType: "bloodDonation",
  },
  {
    fullName: "James Garcia",
    email: "james.garcia@example.com",
    mobileNo: "9876543220",
    gender: "male",
    age: 38,
    bloodGroup: "B+",
    quantity: 1,
    address: "888 Maple Court",
    district: "Jharsuguda",
    pincode: "768001",
    reqPersonAddhar: "123456789022",
    formType: "bloodRequest",
  },
  {
    fullName: "Isabella Martinez",
    email: "isabella.martinez@example.com",
    mobileNo: "9876543221",
    gender: "female",
    age: 24,
    bloodGroup: "AB+",
    quantity: 2,
    address: "999 Elm Road",
    district: "Angul",
    pincode: "759001",
    reqPersonAddhar: "123456789023",
    formType: "bloodDonation",
  },
  {
    fullName: "Liam Wilson",
    email: "liam.wilson@example.com",
    mobileNo: "9876543222",
    gender: "male",
    age: 33,
    bloodGroup: "O-",
    quantity: 1,
    address: "1111 Pine Street",
    district: "Keonjhar",
    pincode: "758001",
    reqPersonAddhar: "123456789024",
    formType: "bloodRequest",
  },
  {
    fullName: "Sophia Anderson",
    email: "sophia.anderson@example.com",
    mobileNo: "9876543223",
    gender: "female",
    age: 26,
    bloodGroup: "A-",
    quantity: 2,
    address: "2222 Elm Avenue",
    district: "Mayurbhanj",
    pincode: "757001",
    reqPersonAddhar: "123456789025",
    formType: "bloodDonation",
  },
  {
    fullName: "Logan Taylor",
    email: "logan.taylor@example.com",
    mobileNo: "9876543224",
    gender: "male",
    age: 39,
    bloodGroup: "B-",
    quantity: 1,
    address: "3333 Oak Lane",
    district: "Nayagarh",
    pincode: "752001",
    reqPersonAddhar: "123456789026",
    formType: "bloodRequest",
  },
  {
    fullName: "Emma Garcia",
    email: "emma.garcia@example.com",
    mobileNo: "9876543225",
    gender: "female",
    age: 23,
    bloodGroup: "AB-",
    quantity: 2,
    address: "4444 Maple Court",
    district: "Nuapada",
    pincode: "766001",
    reqPersonAddhar: "123456789027",
    formType: "bloodDonation",
  },
  {
    fullName: "Noah Martinez",
    email: "noah.martinez@example.com",
    mobileNo: "9876543226",
    gender: "male",
    age: 34,
    bloodGroup: "O+",
    quantity: 1,
    address: "5555 Pine Street",
    district: "Subarnapur",
    pincode: "767001",
    reqPersonAddhar: "123456789028",
    formType: "bloodRequest",
  },
  {
    fullName: "Mia Hernandez",
    email: "mia.hernandez@example.com",
    mobileNo: "9876543227",
    gender: "female",
    age: 27,
    bloodGroup: "A+",
    quantity: 2,
    address: "6666 Elm Avenue",
    district: "Sonepur",
    pincode: "767017",
    reqPersonAddhar: "123456789029",
    formType: "bloodDonation",
  },
  {
    fullName: "Ethan Brown",
    email: "ethan.brown@example.com",
    mobileNo: "9876543228",
    gender: "male",
    age: 36,
    bloodGroup: "B+",
    quantity: 1,
    address: "7777 Oak Lane",
    district: "Dhenkanal",
    pincode: "759001",
    reqPersonAddhar: "123456789030",
    formType: "bloodRequest",
  },
  {
    fullName: "Ava Wilson",
    email: "ava.wilson@example.com",
    mobileNo: "9876543229",
    gender: "female",
    age: 24,
    bloodGroup: "AB+",
    quantity: 2,
    address: "8888 Maple Court",
    district: "Bhadrak",
    pincode: "756100",
    reqPersonAddhar: "123456789031",
    formType: "bloodDonation",
  },
  {
    fullName: "Liam Martinez",
    email: "liam.martinez@example.com",
    mobileNo: "9876543230",
    gender: "male",
    age: 37,
    bloodGroup: "O-",
    quantity: 1,
    address: "9999 Pine Street",
    district: "Jajpur",
    pincode: "755001",
    reqPersonAddhar: "123456789032",
    formType: "bloodRequest",
  },
  {
    fullName: "Sophia Garcia",
    email: "sophia.garcia@example.com",
    mobileNo: "9876543231",
    gender: "female",
    age: 28,
    bloodGroup: "A-",
    quantity: 2,
    address: "10101 Elm Avenue",
    district: "Malkangiri",
    pincode: "764048",
    reqPersonAddhar: "123456789033",
    formType: "bloodDonation",
  },
  {
    fullName: "Logan Lopez",
    email: "logan.lopez@example.com",
    mobileNo: "9876543232",
    gender: "male",
    age: 35,
    bloodGroup: "B-",
    quantity: 1,
    address: "11111 Oak Lane",
    district: "Nabarangpur",
    pincode: "764059",
    reqPersonAddhar: "123456789034",
    formType: "bloodRequest",
  },
  {
    fullName: "Olivia Taylor",
    email: "olivia.taylor@example.com",
    mobileNo: "9876543233",
    gender: "female",
    age: 26,
    bloodGroup: "AB-",
    quantity: 2,
    address: "12121 Maple Court",
    district: "Kendujhar",
    pincode: "758001",
    reqPersonAddhar: "123456789035",
    formType: "bloodDonation",
  },
];
/*
BloodForm.insertMany(dummyData)
  .then(() => {
    console.log("Dummy data inserted successfully.");
    mongoose.connection.close(); // Close the connection after inserting data
  })
  .catch((err) => console.error(err));
*/
module.exports = BloodForm;
