const mongoose = require("mongoose");
const { Schema } = mongoose;
var aggregatePaginate = require("mongoose-aggregate-paginate-v2");

const bloodCampSchema = new mongoose.Schema(
  {
    organizerName: {
      type: String,
      required: true,
    },
    location: {
      type: String,
      required: true,
    },
    date: {
      type: Date,
      required: true,
    },
    donorsCapacity: {
      type: Number,
      required: true,
    },
    contactPerson: {
      type: String,
      required: true,
    },
    contactNumber: {
      type: String,
      required: true,
    },
    organizerAddhar: {
      type: String,
    },
    organizer: {
      type: Schema.Types.ObjectId,
      ref: "User",
    },
    timestamp: {
      type: Date,
      default: Date.now,
    },
  },
  { timestamps: true },
);

bloodCampSchema.plugin(aggregatePaginate);
const BloodCamp = mongoose.model("BloodCamp", bloodCampSchema);

/*

const dummyData = [
  {
    organizerName: "Red Cross Society",
    location: "Bhubaneswar",
    date: "2024-04-20",
    donorsCapacity: 100,
    contactPerson: "John Doe",
    contactNumber: "9876543210",
    organizerAddhar: "123456789012",
  },
  {
    organizerName: "Blood Bank Odisha",
    location: "Cuttack",
    date: "2024-04-22",
    donorsCapacity: 80,
    contactPerson: "Jane Smith",
    contactNumber: "9876543211",
  },
  {
    organizerName: "Lions Club",
    location: "Rourkela",
    date: "2024-04-25",
    donorsCapacity: 120,
    contactPerson: "Michael Johnson",
    contactNumber: "9876543212",
  },
  {
    organizerName: "Rotary Club",
    location: "Puri",
    date: "2024-04-28",
    donorsCapacity: 90,
    contactPerson: "Sarah Brown",
    contactNumber: "9876543213",
  },
  {
    organizerName: "Health Care Foundation",
    location: "Berhampur",
    date: "2024-05-02",
    donorsCapacity: 110,
    contactPerson: "David Clark",
    contactNumber: "9876543214",
  },
  {
    organizerName: "Blood Donors Association",
    location: "Sambalpur",
    date: "2024-05-05",
    donorsCapacity: 70,
    contactPerson: "Emily Taylor",
    contactNumber: "9876543215",
  },
  {
    organizerName: "Apex Blood Bank",
    location: "Brahmapur",
    date: "2024-05-08",
    donorsCapacity: 100,
    contactPerson: "Christopher Martinez",
    contactNumber: "9876543216",
  },
  {
    organizerName: "Angel Blood Society",
    location: "Jharsuguda",
    date: "2024-05-12",
    donorsCapacity: 80,
    contactPerson: "Olivia White",
    contactNumber: "9876543217",
  },
  {
    organizerName: "Youth for Blood",
    location: "Balasore",
    date: "2024-05-15",
    donorsCapacity: 120,
    contactPerson: "Daniel Lee",
    contactNumber: "9876543218",
  },
  {
    organizerName: "Care Foundation",
    location: "Baripada",
    date: "2024-05-18",
    donorsCapacity: 90,
    contactPerson: "Ava Garcia",
    contactNumber: "9876543219",
  },
  {
    organizerName: "Hope Blood Bank",
    location: "Bhadrak",
    date: "2024-05-21",
    donorsCapacity: 110,
    contactPerson: "James Wilson",
    contactNumber: "9876543220",
  },
  {
    organizerName: "Life Saver Foundation",
    location: "Jagatsinghpur",
    date: "2024-05-24",
    donorsCapacity: 70,
    contactPerson: "Sophia Rodriguez",
    contactNumber: "9876543221",
  },
  {
    organizerName: "Humanity Blood Drive",
    location: "Kendujhar",
    date: "2024-05-28",
    donorsCapacity: 100,
    contactPerson: "Logan Martinez",
    contactNumber: "9876543222",
  },
  {
    organizerName: "Helping Hands Society",
    location: "Bargarh",
    date: "2024-06-01",
    donorsCapacity: 80,
    contactPerson: "Isabella Wilson",
    contactNumber: "9876543223",
  },
  {
    organizerName: "Unity Blood Drive",
    location: "Jajpur",
    date: "2024-06-04",
    donorsCapacity: 120,
    contactPerson: "Alexander Anderson",
    contactNumber: "9876543224",
  },
  {
    organizerName: "Save Lives Foundation",
    location: "Rayagada",
    date: "2024-06-08",
    donorsCapacity: 90,
    contactPerson: "Mia Taylor",
    contactNumber: "9876543225",
  },
  {
    organizerName: "Blood Buddies",
    location: "Koraput",
    date: "2024-06-12",
    donorsCapacity: 110,
    contactPerson: "Lucas Brown",
    contactNumber: "9876543226",
  },
  {
    organizerName: "Sunrise Blood Bank",
    location: "Nabarangpur",
    date: "2024-06-16",
    donorsCapacity: 70,
    contactPerson: "Amelia Garcia",
    contactNumber: "9876543227",
  },
  {
    organizerName: "Heal Society",
    location: "Mayurbhanj",
    date: "2024-06-20",
    donorsCapacity: 100,
    contactPerson: "Benjamin Rodriguez",
    contactNumber: "9876543228",
  },
  {
    organizerName: "Blood for All",
    location: "Nuapada",
    date: "2024-06-24",
    donorsCapacity: 80,
    contactPerson: "Emma Anderson",
    contactNumber: "9876543229",
  },
  {
    organizerName: "Care and Share Foundation",
    location: "Subarnapur",
    date: "2024-06-28",
    donorsCapacity: 120,
    contactPerson: "William Martinez",
    contactNumber: "9876543230",
  },
  {
    organizerName: "Golden Hearts Blood Drive",
    location: "Malkangiri",
    date: "2024-07-02",
    donorsCapacity: 90,
    contactPerson: "Chloe Wilson",
    contactNumber: "9876543231",
  },
  {
    organizerName: "Samaritan Blood Bank",
    location: "Angul",
    date: "2024-07-06",
    donorsCapacity: 110,
    contactPerson: "Ethan Brown",
    contactNumber: "9876543232",
  },
  {
    organizerName: "Care for Life",
    location: "Dhenkanal",
    date: "2024-07-10",
    donorsCapacity: 70,
    contactPerson: "Madison Garcia",
    contactNumber: "9876543233",
  },
  {
    organizerName: "Blood Bond",
    location: "Nayagarh",
    date: "2024-07-14",
    donorsCapacity: 100,
    contactPerson: "Noah Rodriguez",
    contactNumber: "9876543234",
  },
  {
    organizerName: "Love for Blood",
    location: "Kandhamal",
    date: "2024-07-18",
    donorsCapacity: 80,
    contactPerson: "Avery Anderson",
    contactNumber: "9876543235",
  },
  {
    organizerName: "Helping Hands Blood Drive",
    location: "Ganjam",
    date: "2024-07-22",
    donorsCapacity: 120,
    contactPerson: "Sofia Martinez",
    contactNumber: "9876543236",
  },
  {
    organizerName: "Life Source Foundation",
    location: "Gajapati",
    date: "2024-07-26",
    donorsCapacity: 90,
    contactPerson: "Jackson Wilson",
    contactNumber: "9876543237",
  },
  {
    organizerName: "Hopeful Hearts Blood Drive",
    location: "Kalahandi",
    date: "2024-07-30",
    donorsCapacity: 110,
    contactPerson: "Lily Brown",
    contactNumber: "9876543238",
  },
  {
    organizerName: "Unity in Blood",
    location: "Jagatsinghpur",
    date: "2024-08-03",
    donorsCapacity: 70,
    contactPerson: "Lucas Garcia",
    contactNumber: "9876543239",
  },
  {
    organizerName: "Blood Angels",
    location: "Kendrapara",
    date: "2024-08-07",
    donorsCapacity: 100,
    contactPerson: "Charlotte Rodriguez",
    contactNumber: "9876543240",
  },
  {
    organizerName: "Red Ribbon Society",
    location: "Sundargarh",
    date: "2024-08-11",
    donorsCapacity: 80,
    contactPerson: "Elijah Anderson",
    contactNumber: "9876543241",
  },
  {
    organizerName: "Life Savers",
    location: "Debagarh",
    date: "2024-08-15",
    donorsCapacity: 120,
    contactPerson: "Harper Martinez",
    contactNumber: "9876543242",
  },
  {
    organizerName: "Health Aid Foundation",
    location: "Boudh",
    date: "2024-08-19",
    donorsCapacity: 90,
    contactPerson: "Aria Wilson",
    contactNumber: "9876543243",
  },
  {
    organizerName: "Blood Brothers",
    location: "Ganjam",
    date: "2024-08-23",
    donorsCapacity: 110,
    contactPerson: "Eli Brown",
    contactNumber: "9876543244",
  },
  {
    organizerName: "Sunshine Blood Bank",
    location: "Rayagada",
    date: "2024-08-27",
    donorsCapacity: 70,
    contactPerson: "Hannah Garcia",
    contactNumber: "9876543245",
  },
  {
    organizerName: "Unity Blood Donors",
    location: "Nayagarh",
    date: "2024-08-31",
    donorsCapacity: 100,
    contactPerson: "Levi Rodriguez",
    contactNumber: "9876543246",
  },
  {
    organizerName: "Saviors Society",
    location: "Bargarh",
    date: "2024-09-04",
    donorsCapacity: 80,
    contactPerson: "Mila Anderson",
    contactNumber: "9876543247",
  },
  {
    organizerName: "Hope for Life",
    location: "Koraput",
    date: "2024-09-08",
    donorsCapacity: 120,
    contactPerson: "Mateo Martinez",
    contactNumber: "9876543248",
  },
  {
    organizerName: "Blood Unity",
    location: "Gajapati",
    date: "2024-09-12",
    donorsCapacity: 90,
    contactPerson: "Ariana Wilson",
    contactNumber: "9876543249",
  },
  {
    organizerName: "Careful Hearts",
    location: "Nabarangpur",
    date: "2024-09-16",
    donorsCapacity: 110,
    contactPerson: "Luca Brown",
    contactNumber: "9876543250",
  },
  {
    organizerName: "Angels of Mercy",
    location: "Kandhamal",
    date: "2024-09-20",
    donorsCapacity: 70,
    contactPerson: "Adalyn Garcia",
    contactNumber: "9876543251",
  },
  {
    organizerName: "Blood Guardians",
    location: "Ganjam",
    date: "2024-09-24",
    donorsCapacity: 100,
    contactPerson: "Asher Rodriguez",
    contactNumber: "9876543252",
  },
  {
    organizerName: "Life Givers Society",
    location: "Boudh",
    date: "2024-09-28",
    donorsCapacity: 80,
    contactPerson: "Camila Anderson",
    contactNumber: "9876543253",
  },
  {
    organizerName: "Hearts United for Blood",
    location: "Rayagada",
    date: "2024-10-02",
    donorsCapacity: 120,
    contactPerson: "Maxwell Martinez",
    contactNumber: "9876543254",
  },
  {
    organizerName: "Angels for Life",
    location: "Debagarh",
    date: "2024-10-06",
    donorsCapacity: 90,
    contactPerson: "Athena Wilson",
    contactNumber: "9876543255",
  },
  {
    organizerName: "Blood Care Alliance",
    location: "Ganjam",
    date: "2024-10-10",
    donorsCapacity: 110,
    contactPerson: "Ryan Brown",
    contactNumber: "9876543256",
  },
];

// Insert dummy data into MongoDB
BloodCamp.insertMany(dummyData)
  .then(() => {
    console.log("Dummy data inserted successfully.");
    mongoose.connection.close(); // Close the connection after inserting data
  })
  .catch((err) => console.error(err));
 */
module.exports = BloodCamp;
