const bloodDonationCamps = [
  {
    location: "Bhubaneswar",
    date: "2023-04-15",
    year: 2023,
    organizer: "Red Cross",
    contact_info: "info@redcross.org",
    blood_type_requirement: "All blood types welcome",
    duration: "10:00 AM - 4:00 PM",
    target_donors: 200,
    special_notes:
      "Please ensure you have eaten a full meal before donating blood.",
    social_media_handles: "#BloodDonationBhubaneswar",
    event_description:
      "Join us in saving lives by donating blood at our annual blood donation camp.",
    volunteer_opportunities: true,
    transportation_assistance: false,
    health_checkup_services: true,
    previous_camp_results: "In our last camp, we collected 180 units of blood.",
  },
  {
    location: "Cuttack",
    date: "2023-06-20",
    year: 2023,
    organizer: "Apollo Hospital",
    contact_info: "info@apollohospital.com",
    blood_type_requirement: "O positive and O negative blood types needed",
    duration: "9:00 AM - 3:00 PM",
    target_donors: 150,
    special_notes:
      "Donors with O blood type are urgently needed due to high demand.",
    social_media_handles: "#ApolloBloodDrive",
    event_description:
      "Help us save lives by donating blood at Apollo Hospital's blood donation camp.",
    volunteer_opportunities: true,
    transportation_assistance: true,
    health_checkup_services: true,
    previous_camp_results:
      "In our last camp, we surpassed our target and collected 170 units of blood.",
  },
  {
    location: "Puri",
    date: "2023-09-10",
    year: 2023,
    organizer: "Odisha Health",
    contact_info: "info@odishahealth.gov.in",
    blood_type_requirement: "A and B blood types preferred",
    duration: "8:00 AM - 2:00 PM",
    target_donors: 180,
    special_notes: "Free health checkups will be provided to all donors.",
    social_media_handles: "#HealthyPuriBloodDrive",
    event_description:
      "Join us in promoting health and wellness by donating blood at the beautiful city of Puri.",
    volunteer_opportunities: true,
    transportation_assistance: false,
    health_checkup_services: true,
    previous_camp_results: "In our last camp, we collected 160 units of blood.",
  },
  {
    location: "Rourkela",
    date: "2023-11-05",
    year: 2023,
    organizer: "Lions Club",
    contact_info: "lionsclubrkl@gmail.com",
    blood_type_requirement: "All blood types welcome",
    duration: "11:00 AM - 5:00 PM",
    target_donors: 220,
    special_notes:
      "Join us in celebrating the spirit of giving by donating blood at Lions Club's blood donation camp.",
    social_media_handles: "#LionsBloodDrive",
    event_description: "Be a hero. Donate blood. Save lives.",
    volunteer_opportunities: true,
    transportation_assistance: true,
    health_checkup_services: true,
    previous_camp_results:
      "In our last camp, we exceeded our target and collected 240 units of blood.",
  },
  {
    location: "Berhampur",
    date: "2024-02-18",
    year: 2024,
    organizer: "Rotary Club",
    contact_info: "info@rotaryberhampur.org",
    blood_type_requirement: "All blood types welcome",
    duration: "9:00 AM - 3:00 PM",
    target_donors: 200,
    special_notes:
      "Your donation can bring a ray of hope to someone in need. Join us!",
    social_media_handles: "#RotaryBloodDrive",
    event_description:
      "Rotary Club invites you to be a part of our life-saving mission at the Berhampur blood donation camp.",
    volunteer_opportunities: true,
    transportation_assistance: false,
    health_checkup_services: true,
    previous_camp_results: "In our last camp, we collected 190 units of blood.",
  },
  {
    location: "Sambalpur",
    date: "2024-05-08",
    year: 2024,
    organizer: "Indian Red Cross Society",
    contact_info: "ircs.sambalpur@gmail.com",
    blood_type_requirement: "All blood types welcome",
    duration: "10:00 AM - 4:00 PM",
    target_donors: 180,
    special_notes:
      "Together, let's make a difference in the lives of those in need. Donate blood today!",
    social_media_handles: "#SambalpurRedCrossDrive",
    event_description:
      "Join Indian Red Cross Society in its noble mission to save lives through blood donation.",
    volunteer_opportunities: true,
    transportation_assistance: true,
    health_checkup_services: true,
    previous_camp_results: "In our last camp, we collected 170 units of blood.",
  },
  {
    location: "Jharsuguda",
    date: "2024-07-12",
    year: 2024,
    organizer: "Jharsuguda Blood Bank",
    contact_info: "jharsugudabloodbank@gmail.com",
    blood_type_requirement: "All blood types welcome",
    duration: "9:00 AM - 3:00 PM",
    target_donors: 150,
    special_notes:
      "Your generosity can give the gift of life to those in need. Donate blood and be a hero!",
    social_media_handles: "#JharsugudaBloodDrive",
    event_description:
      "Join us in saving lives at Jharsuguda Blood Bank's blood donation camp.",
    volunteer_opportunities: true,
    transportation_assistance: false,
    health_checkup_services: true,
    previous_camp_results: "In our last camp, we collected 140 units of blood.",
  },
  {
    location: "Balasore",
    date: "2024-10-30",
    year: 2024,
    organizer: "District Hospital",
    contact_info: "districthospitalbalasore@gmail.com",
    blood_type_requirement: "All blood types welcome",
    duration: "8:00 AM - 2:00 PM",
    target_donors: 180,
    special_notes:
      "Your donation can make a significant impact on someone's life. Join us!",
    social_media_handles: "#BalasoreBloodDrive",
    event_description:
      "District Hospital Balasore invites you to participate in our blood donation camp and help save lives.",
    volunteer_opportunities: true,
    transportation_assistance: true,
    health_checkup_services: true,
    previous_camp_results: "In our last camp, we collected 170 units of blood.",
  },
  {
    location: "Cuttack",
    date: "2025-03-15",
    year: 2025,
    organizer: "Lions Club",
    contact_info: "lionsclubcuttack@gmail.com",
    blood_type_requirement: "All blood types welcome",
    duration: "10:00 AM - 4:00 PM",
    target_donors: 200,
    special_notes:
      "Your contribution can help save multiple lives. Join us in our mission!",
    social_media_handles: "#CuttackLionsBloodDrive",
    event_description:
      "Be a part of Lions Club Cuttack's noble initiative to donate blood and save lives.",
    volunteer_opportunities: true,
    transportation_assistance: false,
    health_checkup_services: true,
    previous_camp_results: "In our last camp, we collected 190 units of blood.",
  },
  {
    location: "Brahmapur",
    date: "2025-06-20",
    year: 2025,
    organizer: "Odisha Blood Bank",
    contact_info: "odishabloodbank@brahmapur.org",
    blood_type_requirement: "All blood types welcome",
    duration: "9:00 AM - 3:00 PM",
    target_donors: 220,
    special_notes:
      "Your generosity can be the lifeline for someone in need. Donate blood and save lives!",
    social_media_handles: "#BrahmapurBloodDrive",
    event_description:
      "Join us in our mission to ensure a steady blood supply for those in need at the Brahmapur blood donation camp.",
    volunteer_opportunities: true,
    transportation_assistance: true,
    health_checkup_services: true,
    previous_camp_results: "In our last camp, we collected 200 units of blood.",
  },
  {
    location: "Rourkela",
    date: "2025-09-10",
    year: 2025,
    organizer: "Rotary Club",
    contact_info: "rotaryclubrourkela@gmail.com",
    blood_type_requirement: "All blood types welcome",
    duration: "8:00 AM - 2:00 PM",
    target_donors: 180,
    special_notes:
      "Your donation can bring hope and healing to those in need. Join us in making a difference!",
    social_media_handles: "#RourkelaRotaryBloodDrive",
    event_description:
      "Rotary Club Rourkela invites you to participate in our blood donation camp and save lives.",
    volunteer_opportunities: true,
    transportation_assistance: false,
    health_checkup_services: true,
    previous_camp_results: "In our last camp, we collected 170 units of blood.",
  },
  {
    location: "Jajpur",
    date: "2026-02-05",
    year: 2026,
    organizer: "Jajpur Health Department",
    contact_info: "healthdeptjajpur@gmail.com",
    blood_type_requirement: "All blood types welcome",
    duration: "9:00 AM - 3:00 PM",
    target_donors: 200,
    special_notes:
      "Your contribution can make a life-saving difference. Join us!",
    social_media_handles: "#JajpurBloodDrive",
    event_description:
      "Jajpur Health Department invites you to be a hero. Donate blood and save lives!",
    volunteer_opportunities: true,
    transportation_assistance: true,
    health_checkup_services: true,
    previous_camp_results: "In our last camp, we collected 190 units of blood.",
  },
  {
    location: "Keonjhar",
    date: "2026-05-18",
    year: 2026,
    organizer: "Keonjhar Red Cross",
    contact_info: "redcrosskeonjhar@gmail.com",
    blood_type_requirement: "All blood types welcome",
    duration: "10:00 AM - 4:00 PM",
    target_donors: 220,
    special_notes:
      "Together, let's ensure no one suffers due to lack of blood. Join us in our mission!",
    social_media_handles: "#KeonjharRedCrossBloodDrive",
    event_description:
      "Be a part of Keonjhar Red Cross's life-saving initiative at the Keonjhar blood donation camp.",
    volunteer_opportunities: true,
    transportation_assistance: true,
    health_checkup_services: true,
    previous_camp_results: "In our last camp, we collected 200 units of blood.",
  },
  {
    location: "Bargarh",
    date: "2026-08-12",
    year: 2026,
    organizer: "Bargarh Blood Bank",
    contact_info: "bargarhbloodbank@gmail.com",
    blood_type_requirement: "All blood types welcome",
    duration: "8:00 AM - 2:00 PM",
    target_donors: 180,
    special_notes:
      "Your donation can be the gift of life for someone in need. Join us!",
    social_media_handles: "#BargarhBloodBankDrive",
    event_description:
      "Bargarh Blood Bank invites you to donate blood and make a difference in someone's life.",
    volunteer_opportunities: true,
    transportation_assistance: false,
    health_checkup_services: true,
    previous_camp_results: "In our last camp, we collected 170 units of blood.",
  },
  {
    location: "Rayagada",
    date: "2027-01-30",
    year: 2027,
    organizer: "Rayagada District Hospital",
    contact_info: "districthospitalrayagada@gmail.com",
    blood_type_requirement: "All blood types welcome",
    duration: "9:00 AM - 3:00 PM",
    target_donors: 200,
    special_notes:
      "Every drop counts. Your blood donation can save a life. Join us!",
    social_media_handles: "#RayagadaBloodDrive",
    event_description:
      "Rayagada District Hospital invites you to donate blood ",
    transportation_assistance: true,
    health_checkup_services: true,
    previous_camp_results: "In our last camp, we collected 190 units of blood.",
  },
  {
    location: "Angul",
    date: "2027-04-25",
    year: 2027,
    organizer: "Angul Lions Club",
    contact_info: "lionsclubangul@gmail.com",
    blood_type_requirement: "All blood types welcome",
    duration: "10:00 AM - 4:00 PM",
    target_donors: 180,
    special_notes:
      "Your blood donation can make a difference. Join us in our mission to save lives!",
    social_media_handles: "#AngulLionsBloodDrive",
    event_description:
      "Angul Lions Club is organizing a blood donation camp to meet the critical need for blood in our community.",
    volunteer_opportunities: true,
    transportation_assistance: false,
    health_checkup_services: true,
    previous_camp_results: "In our last camp, we collected 170 units of blood.",
  },
  {
    location: "Balangir",
    date: "2027-07-18",
    year: 2027,
    organizer: "Balangir Health Department",
    contact_info: "healthdeptbalangir@gmail.com",
    blood_type_requirement: "All blood types welcome",
    duration: "9:00 AM - 3:00 PM",
    target_donors: 190,
    special_notes:
      "Your blood donation can be a lifesaver. Join us at Balangir Health Department's blood donation camp.",
    social_media_handles: "#BalangirHealthBloodDrive",
    event_description: "Be a hero. Donate blood. Save lives.",
    volunteer_opportunities: true,
    transportation_assistance: true,
    health_checkup_services: true,
    previous_camp_results: "In our last camp, we collected 180 units of blood.",
  },
  {
    location: "Baripada",
    date: "2027-10-05",
    year: 2027,
    organizer: "Baripada Red Cross",
    contact_info: "redcrossbaripada@gmail.com",
    blood_type_requirement: "All blood types welcome",
    duration: "8:00 AM - 2:00 PM",
    target_donors: 200,
    special_notes:
      "Your blood donation can make a significant impact on someone's life. Join us!",
    social_media_handles: "#BaripadaRedCrossDrive",
    event_description:
      "Baripada Red Cross invites you to donate blood and save lives at our blood donation camp.",
    volunteer_opportunities: true,
    transportation_assistance: false,
    health_checkup_services: true,
    previous_camp_results: "In our last camp, we collected 190 units of blood.",
  },
  {
    location: "Bhadrak",
    date: "2028-03-20",
    year: 2028,
    organizer: "Bhadrak Blood Bank",
    contact_info: "bhadrakbloodbank@gmail.com",
    blood_type_requirement: "All blood types welcome",
    duration: "10:00 AM - 4:00 PM",
    target_donors: 220,
    special_notes:
      "Your blood donation can be a lifeline for someone in need. Join us at Bhadrak Blood Bank's blood donation camp.",
    social_media_handles: "#BhadrakBloodBankDrive",
    event_description: "Be a hero. Donate blood. Save lives.",
    volunteer_opportunities: true,
    transportation_assistance: true,
    health_checkup_services: true,
    previous_camp_results: "In our last camp, we collected 210 units of blood.",
  },
  {
    location: "Boudh",
    date: "2028-06-15",
    year: 2028,
    organizer: "Boudh Health Society",
    contact_info: "healthsocietyboudh@gmail.com",
    blood_type_requirement: "All blood types welcome",
    duration: "9:00 AM - 3:00 PM",
    target_donors: 180,
    special_notes:
      "Your blood donation can make a difference. Join us in our mission to save lives!",
    social_media_handles: "#BoudhHealthBloodDrive",
    event_description:
      "Boudh Health Society is organizing a blood donation camp to meet the critical need for blood in our community.",
    volunteer_opportunities: true,
    transportation_assistance: false,
    health_checkup_services: true,
    previous_camp_results: "In our last camp, we collected 170 units of blood.",
  },
  {
    location: "Debagarh",
    date: "2028-09-08",
    year: 2028,
    organizer: "Debagarh Red Cross",
    contact_info: "redcrossdebagarh@gmail.com",
    blood_type_requirement: "All blood types welcome",
    duration: "8:00 AM - 2:00 PM",
    target_donors: 190,
    special_notes:
      "Your blood donation can make a significant impact on someone's life. Join us!",
    social_media_handles: "#DebagarhRedCrossDrive",
    event_description:
      "Debagarh Red Cross invites you to donate blood and save lives at our blood donation camp.",
    volunteer_opportunities: true,
    transportation_assistance: true,
    health_checkup_services: true,
    previous_camp_results: "In our last camp, we collected 180 units of blood.",
  },
  {
    location: "Dhenkanal",
    date: "2028-12-01",
    year: 2028,
    organizer: "Dhenkanal District Hospital",
    contact_info: "districthospitaldhenkanal@gmail.com",
    blood_type_requirement: "All blood types welcome",
    duration: "10:00 AM - 4:00 PM",
    target_donors: 220,
    special_notes:
      "Your blood donation can be a lifeline for someone in need. Join us at Dhenkanal District Hospital's blood donation camp.",
    social_media_handles: "#DhenkanalDistrictHospitalDrive",
    event_description: "Be a hero. Donate blood. Save lives.",
    volunteer_opportunities: true,
    transportation_assistance: true,
    health_checkup_services: true,
    previous_camp_results: "In our last camp, we collected 210 units of blood.",
  },
  {
    location: "Gajapati",
    date: "2029-02-25",
    year: 2024,
    organizer: "Gajapati Blood Bank",
    contact_info: "bloodbankgajapati@gmail.com",
    blood_type_requirement: "All blood types welcome",
    duration: "9:00 AM - 4:00 PM",
    target_donors: 180,
    special_notes:
      "Your donation can make a significant impact. Join us in our life-saving mission!",
    social_media_handles: "#GajapatiBloodDrive",
    event_description:
      "Be a hero, donate blood! Gajapati Blood Bank's blood donation camp awaits your generous contribution.",
    volunteer_opportunities: true,
    transportation_assistance: false,
    health_checkup_services: true,
    previous_camp_results: "In our last camp, we collected 170 units of blood.",
  },
  {
    location: "Ganjam",
    date: "2029-05-20",
    year: 2029,
    organizer: "Ganjam Lions Club",
    contact_info: "lionsclubganjam@gmail.com",
    blood_type_requirement: "All blood types welcome",
    duration: "10:00 AM - 3:00 PM",
    target_donors: 220,
    special_notes:
      "Your contribution can bring hope to those in need. Donate blood and save a life!",
    social_media_handles: "#GanjamLionsBloodDrive",
    event_description:
      "Join Ganjam Lions Club in its noble mission of saving lives through blood donation.",
    volunteer_opportunities: true,
    transportation_assistance: true,
    health_checkup_services: true,
    previous_camp_results:
      "In our last camp, we exceeded our target and collected 240 units of blood.",
  },
  {
    location: "Jagatsinghpur",
    date: "2029-08-15",
    year: 2029,
    organizer: "Jagatsinghpur Health Department",
    contact_info: "healthdeptjagatsinghpur@gmail.com",
    blood_type_requirement: "All blood types welcome",
    duration: "9:00 AM - 3:00 PM",
    target_donors: 180,
    special_notes:
      "Join us in saving lives. Your blood donation can make a difference!",
    social_media_handles: "#JagatsinghpurHealthDrive",
    event_description:
      "Jagatsinghpur Health Department invites you to donate blood and contribute to the health and well-being of the community.",
    volunteer_opportunities: true,
    transportation_assistance: true,
    health_checkup_services: true,
    previous_camp_results: "In our last camp, we collected 170 units of blood.",
  },
  {
    location: "Kalahandi",
    date: "2029-11-10",
    year: 2029,
    organizer: "Kalahandi Red Cross",
    contact_info: "redcrosskalahandi@gmail.com",
    blood_type_requirement: "All blood types welcome",
    duration: "8:00 AM - 2:00 PM",
    target_donors: 190,
    special_notes:
      "Your donation can make a significant impact. Join us in our life-saving mission!",
    social_media_handles: "#KalahandiBloodDrive",
    event_description:
      "Be a hero, donate blood! Kalahandi Red Cross's blood donation camp awaits your generous contribution.",
    volunteer_opportunities: true,
    transportation_assistance: false,
    health_checkup_services: true,
    previous_camp_results: "In our last camp, we collected 180 units of blood.",
  },
];

export default bloodDonationCamps;
